### PR TITLE
Remove unused cloudwatch

### PR DESCRIPTION
**Pull request by paololim**
Cloudwatch was added sometime a year ago to collect metrics for every request that goes through proxy which is passed to subsequent services. Information here is already duplicated in our Graphite metrics implementations. In the meantime, this is a decent contributor to our monthly AWS bill:

screen shot 2018-02-27 at 1 16 03 pm

### CODE REVIEW

**Comment by benwaffle** [comment]
At 18,000,000 metrics, our bill is only 18,000,000/1000*.01 = $180 for proxy. I believe most of the requests come from Vivid Cortex, although that would make (115,921,907-18,000,000)/30/24/60/60 = 37 requests/sec from vivid. (please correct me if i'm wrong)

If we implemented proxy metrics correctly we could have nice dashboards showing response time for each service/route.

**Comment by paololim** [comment]
>If we implemented proxy metrics correctly we could have nice dashboards showing response time for each service/route.
I believe we should already have this in hosted graphite?

**Comment by paololim** [comment]
I think these ones are definitely produced by proxy, as it is implemented right now:

screen shot 2018-02-27 at 1 48 40 pm

**Comment by benwaffle** [comment]
> I believe we should already have this in hosted graphite?

True, but it's only implemented if you add the libs to the service. Also, does it make a difference if the service is measuring it vs proxy?

**Comment by paololim** [comment]
>Also, does it make a difference if the service is measuring it vs proxy?

No it does not, but just seems redundant now - and we don't really use these metrics as is anyway.

**Pull request merged**
