### PR TITLE
Increase max content length for json payload from 100KB to 5MB

### PR DESCRIPTION
**Pull request by gheine**
See https://www.playframework.com/documentation/2.6.x/ScalaBodyParsers

### CODE REVIEW

**Comment by ericluria** [comment]
What's the purpose of this change? Also wondering if we should be worried about running out of memory if there's any chance we'd store 100s of 5mb requests in memory.

**Comment by gheine** [comment]
Need to get export requests with payloads ~1MB processed for farfetch.
If it's a concern we can dial it back afterwards?

**Comment by dasmb** [comment]
LGTM. However, I notice Proxy isn't up in HostedGraphite, so I don't know what current heap and non-heap usage looks like on the cluster.

Given this change will increase memory pressure, suggest we get it into HG soon so we can catch memory issues before we start losing user requests. LMK if you want me to do so for you.

**Comment by gheine** [comment]
Actually was able to make this change in search only and issue the request directly to search.api.flow.io

**Pull request closed without merging**
