### PR TITLE
Add timing headers

### PR DESCRIPTION
**Pull request by jlogeart**
This PR introduces new response headers to all requests:

 - `X-Flow-Proxy-Response-Time`: the total time in ms it took to process the request
 - `X-Flow-Proxy-Service-Timing`: the name and response time in ms for a service. E.g., bundle-checkout;414

### Verification plan

 - [ ] New headers are present on each successful calls
 - [ ] Other headers are unchanged

### CODE REVIEW

**Comment by benwaffle** [comment]
Can't you do the same thing by searching the trace ID in sumo?
And is ResponseTime - ServiceTime supposed to tell you how much time is spent in proxy?

**Review by mbryzek — APPROVED** [review]

**Comment by jlogeart** [comment]
@benwaffle 

> Can't you do the same thing by searching the trace ID in sumo?

Not sure what you mean. I want to make the timing available in the headers.

> And is ResponseTime - ServiceTime supposed to tell you how much time is spent in proxy?

Given what `X-Flow-Proxy-Response-Time` and `X-Flow-Proxy-Service-Timing`, that is correct.

**Comment by benwaffle** [comment]
>Not sure what you mean. I want to make the timing available in the headers.

I mean that you can look up how long a request took in sumo.

Is there any context for this PR?

**Comment by paololim** [comment]
yeah, some additional context around what problem you are debugging here would be ideal. but otherwise, i dont mind.

**Review by paololim — APPROVED** [review]

**Comment by jlogeart** [comment]
@benwaffle Context is to be able to automatically track times as reported by proxy. For instance by a tool like catch point.

**Comment by paololim** [comment]
@jlogeart just as long as it is clear this is simply the time it takes for the request in our infrastructure - and doesn't include time of the request and response to get back to the caller, which could be significantly longer.

**Comment by jlogeart** [comment]
@paololim Yes, we also want to set up RUM, and timings between our reverse proxy service and this proxy.

**Pull request merged**
