### PR TITLE
Proxy request headers on request envelope

### PR DESCRIPTION
**Pull request by mbryzek**

### CODE REVIEW

**Comment by mbryzek** [comment]
@paololim can you review? not sure how to verify 100% that wms label printing will be fine

**Comment by mbryzek** [comment]
@jlogeart @chrhicks this will allow headers to be forwarded when using the request env

**Comment by paololim** [comment]
I *think* it looks good, but i can manually test in production later tonight/after you deploy.

**Comment by mbryzek** [comment]
@jlogeart @chrhicks this will allow headers to be forwarded when using the request environment(which then should enable us to use post w/ request envelope for charles+colvards)

**Pull request merged**
