### PR TITLE
Allow crawlers to load sessions

### PR DESCRIPTION
**Pull request by benwaffle**
@garethgd

### CODE REVIEW

**Comment by garethgd** [comment]
@mbryzek According to Google's rich snippet tool: https://search.google.com/test/rich-results?view=fetch-info&id=MNS_6V2llOHBKIspc55q3A `https://api.flow.io/shopify/shops/flow-sandbox.myshopify.com/sessions?envelope=request` is blocked by robots.txt.

Without the session endpoint hit, the correct experience isn't configured correctly.  This causes the tool to not have access to localized schema data which is generated from `shopify-connect`.

Allowing this in `robots.txt` will hopefully allow the testing tool to detect the localized schema and will validate our schema working for the client's product ads.

**Comment by mbryzek** [comment]
For the URL in question:
```
$ curl 'https://api.flow.io/shopify/shops/flow-sandbox.myshopify.com/sessions?envelope=request'
{"code":"generic_error","messages":["Envelope requests require a valid JSON body"]}
```

allowing access to a GET will just return an error.

If google is posting - that would mean crawler is creating sessions (which we don't want).

Can you share if the current configuration is an actual problem and if so why?

**Comment by chrhicks** [comment]
@mbryzek Google is simply loading the storefront with a regular browser (a 'Google smartphone'). You can assume it's doing the POST w/ the correct data. Given that it's a bot, google is simply following their own guidelines and opting not to pursue the request as it was not allowed in `robots.txt`.

**Comment by mbryzek** [comment]
agreement to limit to user agent "Googlebot" - monitor traffic to session post deploy

**Comment by RoryH** [comment]
> If google is posting - that would mean crawler is creating sessions (which we don't want).

Should we consider a feature being a transient session for crawlers to allow them load a page and localize prices and/or schema data? It would only need to live for the life of the page load.

**Pull request merged**
